config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

get 'createMeeting' => 'meetings#createMeeting'
get 'otherUserMeeting' => 'meetings#otherUserMeeting'
get 'allMeetings' => 'meetings#allMeetings'

root 'static_pages#home'
get 'help' => 'static_pages#help'
get 'contacts' => 'static_pages#contacts'
get 'about' => 'static_pages#about'
get 'signup' => 'users#new'
get 'newmeeting' => 'meetings#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

 resources :meetings

 get 'destroy' => 'meetings#destroy'
 get 'destroy' => 'users#destroy'

 resources :users do
    member do
      get :following, :followers
    end
  end

   resources :meetings do
    member do
         get :following
    end
  end

resources :relationships,       only: [:create, :destroy]
resources :relates,       only: [:create, :destroy]

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  
  end

  def help
  end

def about
end


end

app/helpers/static_pages_helper.rb
module StaticPagesHelper

def full_title(page_title = '')
	base_title = "Missing title"
	if page_title.empty?
		base_title
	else 
		"#{page_title}"
	end
end





end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
  </head>
  <body>
    <h1>About</h1>
    <p>
      The <a href="http://www.railstutorial.org/"><em>Ruby on Rails
      Tutorial</em></a> is a
      <a href="http://www.railstutorial.org/book">book</a> and
      <a href="http://screencasts.railstutorial.org/">screencast series</a>
      to teach web development with
      <a href="http://rubyonrails.org/">Ruby on Rails</a>.
      This is the sample application for the tutorial.
    </p>
  </body>
</html>

app/views/static_pages/contacts.html.erb
<% provide(:title, 'Contact') %>
<div class="contactDiv">


<div class ="rightSide">You can contact me using the form to your left, 
	alternatively you can use one of the links below:</br>

 </br></br>   +44 (0) 7540 429083</br>
  </br>  hello@joe-macdonald.co.uk</br>
  </br>  joseph.macdonald17</br>
   </br> twitter.com/josephmacdonald</br>

</div>

<div class="theMap">

<div style="width: 400px"><iframe width="400" height="400" src="http://regiohelden.de/google-maps/map_en.php?width=400&amp;height=400&amp;hl=en&amp;q=Sofia%2CDateks+(Dateks)&amp;ie=UTF8&amp;t=&amp;z=16&amp;iwloc=A&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"><a href="http://www.regiohelden.de/google-maps/">Google Maps Generator</a> von <a href="http://www.regiohelden.de/">RegioHelden</a></iframe><br /><span style="font-size: 9px;"><a href="http://www.regiohelden.de/google-maps/" style="font-size: 9px;">Google Maps Generator</a> by <a href="http://www.regiohelden.de/" style="font-size: 9px;">RegioHelden</a></span></div>
</div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help")%>


    <title><%= yield(:title)%> </title>

  	<div class= "outerDiv">
<div class= "helpDiv">Searching for help </br></br></br>
No matter what you're looking for, start with a simple search like where's the closest Ruby cours?. You can always add a few descriptive words if necessary.</div>


<div class= "helpDiv">Find your answers </br></br></br>
This page lists some locations where you can ask questions or make comments.</div>
<div class= "helpDiv">Manage answers </br></br></br>
The Questions & Answers (Q&A) feature is a great tool to build a community around your product. It allows customers to post public questions and receive support from agents or other customers.</div>
</div>

app/views/static_pages/home.html.erb
<%provide(:title, "Home")%>

    <title> <%= yield(:title)%> </title>
<div class= "welcomText">Welcome</div>

   <div class=" jumbotron" style="display:inline; float:left; background-color:transparent">

<%= link_to root_path do %>
<div class="meetingThumbnail" style = "background-color:#4169E1"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Home</h3>  <div style = "padding:5px;color:white">Click here and I am hoing to take you Home</div></div>
<%end %>


<% if logged_in? %>
<%=link_to current_user do %>
<div class="meetingThumbnail" style = "background-color:#FF6666"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Log in</h3>  <div style = "padding:5px;color:white">Log in from here</div></div>
<% end %>

<% else %>
<%= link_to login_path do %>
<div class="meetingThumbnail" style = "background-color:#FF6666"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Log in</h3>  <div style = "padding:5px;color:white">Log in from here</div></div>
<% end %>

<%	end %>


<%= link_to contacts_path do %>
<div class="meetingThumbnail" style = "background-color:#990099; width: 150px;"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Contacts</h3>  <div style = "padding:5px;color:white">In case you need to contact me</div></div> 
<% end %>

<%= link_to about_path do%>
<div class="meetingThumbnail" style = "background-color:#4169E1"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">About</h3>  <div style = "padding:5px;color:white">Click here and I will tell you about me</div></div> 
<% end %>

<%if logged_in?%>
<%= link_to current_user do %>
<div class="meetingThumbnail" style = "background-color:#330099"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Profile</h3>  <div class = "divProfile"></div></div>
<% end %>
<%else%>
<%= link_to login_path do %>
<div class="meetingThumbnail" style = "background-color:#330099"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Profile</h3>  <div class = "divProfile"></div></div>
<% end %>
<% end %>

<%= link_to help_path do %>
<div class="meetingThumbnail" style = "background-color:#009933; text-alaign:center; width:140px;" > <h3 style= "color:white; margin-top:2px;margin-left:5px;">HELP</h3>  <div style = "padding:5px;color:white"></div></div>
<%end%>


<%= link_to  do %>
<div class="meetingThumbnail" style = "background-color:#6699FF; text-alaign:center"> <div class="facebookUrl"></div> <div style = "padding:5px;color:white"></div></div>
<%end%>


<%= link_to  do %>
<div class="meetingThumbnail" style = "background-color:#006666; text-alaign:center; width:210px;"> <div class="twitterUrl"></div>  <div style = "padding:5px;color:white"></div></div>
<%end%>





<%if logged_in?%>

<%= link_to allMeetings_path do %>
<div class="meetingThumbnail" style = "background-color:#BDB76B; width:180px;"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Meeting Groups</h3><div style = "padding:5px;color:white">See all the meeting groups here</div></div>
<% end %>
<%end %>

<%= link_to signup_path do %>
<div class="meetingThumbnail" style = "background-color:#DAA520; text-alaign:center; width:220px;" > <h3 style= "color:white; margin-top:15px;margin-left:50px;">SIGN UP</h3> <div style = "padding:5px;color:white" > Sigh up from here </div>  <div style = "padding:5px;color:white"></div></div>
<%end%>

<% if  logged_in? %>

<%= link_to edit_user_path(current_user) do %>
<div class="meetingThumbnail" style = "background-color:#FF4500; text-alaign:center;width:150px;"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Edit my profile </h3>  <div style = "padding:5px;color:white">Click here to change your profile intormation</div></div>
<% end %>



<% end %>

<% if logged_in? %>

<%= link_to users_path do %>
<div class="meetingThumbnail" style = "background-color:#BDB76B; width:200px;"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">All members</h3><div style = "padding:5px;color:white">See all the members here</div></div>
<% end%>



<%end %>

<% if logged_in? %>

<%= link_to meetings_path do %>
<div class="meetingThumbnail" style = "background-color:#BDB76B; width:200px;"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Create a meeting</h3><div style = "padding:5px;color:white">Create meeting</div></div>
<% end%>
<% end%>


<% if  logged_in? %>

<%= link_to logout_path do %>
<div class="meetingThumbnail" style = "background-color:#A00000; text-alaign:center;width:150px;"> <h3 style= "color:white; margin-top:2px;margin-left:5px;">Log out </h3>  <div style = "padding:5px;color:white">See you next time</div></div>
<% end %>
<%end%>
</div>