config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

get 'createMeeting' => 'meetings#createMeeting'
get 'otherUserMeeting' => 'meetings#otherUserMeeting'
get 'allMeetings' => 'meetings#allMeetings'

root 'static_pages#home'
get 'help' => 'static_pages#help'
get 'contacts' => 'static_pages#contacts'
get 'about' => 'static_pages#about'
get 'signup' => 'users#new'
get 'newmeeting' => 'meetings#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

 resources :meetings

 get 'destroy' => 'meetings#destroy'
 get 'destroy' => 'users#destroy'

 resources :users do
    member do
      get :following, :followers
    end
  end

   resources :meetings do
    member do
         get :following
    end
  end

resources :relationships,       only: [:create, :destroy]
resources :relates,       only: [:create, :destroy]

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  belongs_to :user

has_many :relates, foreign_key: "followed_id", dependent: :destroy
has_many :user_followers, through: :relates, source: :follower


  default_scope -> { order(created_at: :desc) }
     validates :user_id, presence: true
      validates :content, presence: true, length: { maximum: 1000 }
      validates :place, presence: true, length: { maximum: 50 }
      validates :thedate, presence: true, length: { maximum: 10 }
       mount_uploader :picture, PictureUploader


validates_format_of :thedate, :with => /\d{2}\/\d{2}\/\d{4}/, :message => "^Date must be in the following format: mm/dd/yyyy"

def picture_size
	if picture_size>3.megabytes
		errors.add(:picture, "Pictures must be less than 3MB")
	end
end



#   # Unfollows a user.
#   def unfollowss(other_meeting)
#     active_relates.find_by(meeting_id: other_meeting.id).destroy
#   end

#   # Returns true if the current user is following the other user.
#   def followingss?(other_meeting)
#     meetings.include?(other_meeting)
#   end


 
 def feed
  following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Meeting.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

 def following?(meeting)
    relates.find_by_followed_id(meeting.id)
  end

end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :createMeeting, :following]
  before_action :correct_user,   only: :destroy



    
      def index
     @user = User.all
      @meetings = @user.find(params[:user_id])
  
  

    end

  def show
      
        @meetings = Meeting.find(params[:id])
        if  @meetings.destroy
             flash[:success] = "Meeting deleted"
        end
     
   redirect_to  current_user

    @users = current_user.following.paginate(page: params[:page])
end
  

def new 
  @meetings = Meeting.new
end

  def create
    
   @meetings = current_user.meetings.build(meeting_params)
   if @meetings.save
     flash[:success] = "Meeting created!"
     redirect_to @current_user


    else
 
   render 'index'
    end
  end 
 

def thePicture
  @picture = Meeting.find(params[:picture])
  @thePicture = @picture.resize('big.jpg', 'small.jpg', 300, 300)
end


 def createMeeting 
@user = User.find(session[:user_id])
  @meetingss = @user.meetings

end






def allMeetings
 @meetings = Meeting.all

end


def otherUserMeeting

@meetings = Meeting.all
end


  def destroy
    @meetings.destroy
    flash[:success] = "Meeting deleted"
   redirect_to  'static_pages#home'
  end


 def following
    @title = "Following"

    @meeting = Meeting.find(params[:id])
 
    @users = @meeting.user_followers.paginate(page: params[:page])
    render 'show_follow'
  end



  

  private

    def meeting_params
      params.require(:meeting).permit(:content, :place, :thedate, :picture, :user_id)
    end

 def correct_user
      @meetings = current_user.meetings.find_by(id: params[:id])
  
    end

end

app/views/meetings/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/meetings/_meetings.html.erb
  <% @meetings.each do |meeting| %>




<%if current_user?(@user)%>

<%= link_to createMeeting_path do %>

   <div class = "singleMeeting" >
  <div style = "float:left; position:absolute; ; z-index:-1;"> <%= image_tag meeting.picture.url, :width=>300, :height=>300  if meeting.picture? %></div>
  	  <div class = "meetingText" style = "z-index:-1;"><%= meeting.content.truncate(25, omission: '... (continued)') %></div>
 	

    <div style = "color:black; display:inline; float:left; margin-top:40px; margin-left:10px;z-index:1; color: white">Posted <%= time_ago_in_words(meeting.created_at) %> ago.</div>

  </div>
<%end%>


  <% else if current_user != (@user) %>
  <%= link_to otherUserMeeting_path do %>

   <div class = "singleMeeting" >
  <div style = "float:left; position:absolute; ; z-index:-1;"> <%= image_tag meeting.picture.url, :width=>300, :height=>300  if meeting.picture? %></div>
  	  <div class = "meetingText" style = "z-index:-1;"><%= meeting.content.truncate(25, omission: '... (continued)') %></div>
 	

    <div style = "color:black; display:inline; float:left; margin-top:40px; margin-left:10px;z-index:1; color: white">Posted <%= time_ago_in_words(meeting.created_at) %> ago.</div>

  </div>
<%end%>
<%end%>
<%end%>
<%end%>

app/views/meetings/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/meetings/allMeetings.html.erb
  
<% provide(:title, 'All meetings') %>

  <% @meetings.each do |meeting| %>


   <div class = "singleMeetingInAll">
   	 <div style = "margin-left:240px;">  <%= image_tag meeting.picture.url, :width=> 500, :height => 300 if meeting.picture? %></div>
 <div style = "color:black; margin-left:10px;margin-bottom:20px;">Posted <%= time_ago_in_words(meeting.created_at) %> ago.</div>


  	<%= link_to meeting.user do%><b>
    	<div class = "meetingTextAll" >Posted by: <%=  meeting.user.name%></div>
    <% end %>


      <div class = "meetingTextAll" >Place: <%= meeting.place %></div>
    <div style="">  <div class = "meetingTextAll">Date: <%= meeting.thedate %></div>
    <div class = "meetingTextAll">About: <%= meeting.content %></div></b>

   <% @user ||= current_user %>
  <a href="<%= following_meeting_path(meeting)  %>" style= "color:black;">
 <b>   <div style = "color:black display:inline;float:left;margin-right:10px;">
      <div style = "margin-top:10px;padding-bottom:10px;"><%= meeting.user_followers.count %>
    Going</div>
  </b></a>
</div>




  <% unless current_user?meeting.user%>
<% if current_user.followings?(meeting) %>
    <%= form_for(current_user.relates.find_by_followed_id(meeting),
              html: { method: :delete }) do |f| %>
   <%= f.submit "LEAVE", class: "btn btn-large" %>
 <% end %>
  <% else %>
    <%= form_for(current_user.relates.build(followed_id: meeting.id)) do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <%= f.submit "JOIN", class: "btn btn-large btn-primary" %>
<% end %>
  <% end %>

<% end %> 

</div>
</div>





<%end %>

app/views/meetings/createMeeting.html.erb
 <% provide(:title, 'My meetings') %>
  <% @meetingss.each do |meeting| %>

   <div class = "singleMeetingInAll">
  <div style = "margin-left:240px;">  <%= image_tag meeting.picture.url, :width=> 500, :height => 300 if meeting.picture? %></div>

   
      <div style = "color:black; ">Posted <%= time_ago_in_words(meeting.created_at) %> ago.</div><div style = "">

      <% if current_user?(@user)%>  
   <%= link_to "delete", meeting, method: :destroy,   data: { confirm: "You sure?" } %>
   <%end%>


</div>
<b> <div class = "meetingTextAll">Place: <%= meeting.place %></div>
  <div class = "meetingTextAll">Date: <%= meeting.thedate %></div>
      <div class = "meetingTextAll">About: <%= meeting.content %></div></d>





  </div>

<%end %>

app/views/meetings/new.html.erb
<%= form_for(@meetings) do |f| %>
<%= render 'shared/meeting_error_messages', object: f.object %>

  <div class="field">
  	<div style = "color: white"> <%= f.label :"Information about the meeting" %></div><br>
    <%= f.text_area :content, placeholder: "About information..." %>
  </div>

    <div class="field">
  <div style = "color:White;">  <%= f.label :place %></div><br>
    <%= f.text_field :place,  class: 'form-control'%>
  </div>

  <div class="field">
 <div style = "color: white">   <%= f.label :thedate %></div><br>
    <%= f.text_field :thedate, placeholder: "Example: 01/01/2015" %>
  </div>
 <%= f.file_field :picture,  class: 'form-control' %>
  <%= f.submit "Create", class: "btn btn-primary" %>

<% end %>

app/views/meetings/otherUserMeeting.html.erb
  <% provide(:title, 'Other meetings') %>
  <% @meetings.each do |meeting| %>


   <div class = "singleMeetingInAll">
  <div style = "margin-left:240px;">  <%= image_tag meeting.picture.url, :width=> 500, :height => 300 if meeting.picture? %></div>

   
      <div style = "color:black; ">Posted <%= time_ago_in_words(meeting.created_at) %> ago.</div><div style = "">

      <% if current_user?(@user)%>  
   <%= link_to "delete", meeting, method: :destroy,   data: { confirm: "You sure?" } %>
   <%end%>


</div>
<b> <div class = "meetingTextAll">Place: <%= meeting.place %></div>
  <div class = "meetingTextAll">Date: <%= meeting.thedate %></div>
      <div class = "meetingTextAll">About: <%= meeting.content %></div></d>





  </div>

<%end %>

app/views/meetings/show.html.erb
Asadas

app/views/meetings/show_follow.html.erb
<% provide(:title, @title) %>



      <% if @meeting.user_followers.any? %>
       <h3 style= "color:white"> Going users:</h3>
          <% @users.each do |user| %>

         <div class="followersGravatars">

        <div >    <%= link_to gravatar_for(user, size: 70), user %></div>
        <div >   <h3 style="color:white"> User: <%= user.name %></h3></div>
   </div>
          <%end%>
          
     
      <% end %>