config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

get 'createMeeting' => 'meetings#createMeeting'
get 'otherUserMeeting' => 'meetings#otherUserMeeting'
get 'allMeetings' => 'meetings#allMeetings'

root 'static_pages#home'
get 'help' => 'static_pages#help'
get 'contacts' => 'static_pages#contacts'
get 'about' => 'static_pages#about'
get 'signup' => 'users#new'
get 'newmeeting' => 'meetings#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  get 'logout'  => 'sessions#destroy'

 resources :meetings

 get 'destroy' => 'meetings#destroy'
 get 'destroy' => 'users#destroy'

 resources :users do
    member do
      get :following, :followers
    end
  end

   resources :meetings do
    member do
         get :following
    end
  end

resources :relationships,       only: [:create, :destroy]
resources :relates,       only: [:create, :destroy]

end

app/models/user.rb
class User < ActiveRecord::Base
has_many :meetings, dependent: :destroy




	attr_accessor :remember_token
 before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 30 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 50 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, length: { minimum: 6 }, allow_blank: true

  has_many :active_relationships,  class_name:  "Relationship",
                                   foreign_key: "follower_id",
                                   dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :followers, through: :passive_relationships, source: :follower


validates_format_of :name, :with => /\A[^0-9`!@#\$%\^&*+_=]+\z/


has_many :relates, foreign_key: "follower_id", dependent: :destroy
has_many :followed_meetings, through: :relates, source: :followed

   def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
   def User.new_token
    SecureRandom.urlsafe_base64
  end
   def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
   def forget
    update_attribute(:remember_digest, nil)
  end

 def feed
  following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Meeting.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end



  # Follows a user.
   def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end



  def followings?(meeting)
relates.find_by_followed_id(meeting.id)
  end

def follows!(meeting)
relates.create!(followed_id: meeting.id)
end



def unfollows!(meeting)
relates.find_by_followed_id(meeting.id).destroy

end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
     before_action :logged_in_user, only: [:index, :edit, :destroy, :update, :following, :followers]
     before_action :correct_user,   only: [:edit, :update, :destroy  ]
def home
 
end

  def new
    @user = User.new
  end

 def index
    @users = User.paginate(page: params[:page])

  end

def show

  @user = User.find(params[:id])
  @users = User.all
  @meetings = @user.meetings.paginate(page: params[:page])


end


  def edit
    @user = User.find(params[:id])
end

def create 
  @user = User.new(user_params)
  if @user.save
    log_in @user
      flash[:success] = "Welcome!"
      redirect_to @user
  else
 render 'new'
  end
end


  def destroy
 @user = User.find params[:id]
   @user.destroy
   

    respond_to do |format|
      format.html { redirect_to(root_url) }
      format.xml  { head :ok }
    end
  end

def update
@user = User.find(params[:id])
if @user.update_attributes(user_params)
  flash[:success] = "Updated successfully"
  redirect_to @user
else 
  render 'edit'
end
end



def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

 def createMeeting
     @user = User.find(params[:id])
  end



   def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end



private 

def user_params
 params.require(:user).permit(:name, :email, :password, :password_confirmation, :created_at)
  end

  

 def correct_user
      @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
    end





  end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end




def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end

end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
<div style= "width:100px;margin-top:10px;"> <%= f.submit "Follow"%></div>
<% end %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation" >
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }) do |f| %>
 <div style= "width:100px;margin-top:10px;"> <%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target=_blank>change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1 style = "color:white; margin-left:100px;">All users</h1>


<%= will_paginate %>
<ul class="users" >
  <% @users.each do |user| %>
 <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
</li>
 <%= user.name%> registerd at <%=raw user.created_at %>
 <div >____________________________</div>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1 style="margin-left:290px; color: black;">Sign up</h1>
<div style="height:30px;"></div>

<div class="row" >
  <div class="col-md-6 col-md-offset-3">

   <%= form_for(@user) do |f| %>
 <%= render 'shared/error_messages' %>

	<div style="color:black"><%= f.label :name%></div>
	<%= f.text_field :name, :placeholder => 'John', class: 'form-control'%>

      <div style= "color:black"><%= f.label :email %></div>
      <%= f.email_field :email, :placeholder => ' user@example.com', class: 'form-control' %>

     <div style = "color:black"> <%= f.label :password %></div>
      <%= f.password_field :password, class: 'form-control' %>

     <div style="color: black"> <%= f.label :password_confirmation, "Confirmation" %></div>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

    <div style="margin-top:15px;">  <%= f.submit "Create my account", class: "btn btn-primary" %></div>
    <% end %>
  </div>

</div>

app/views/users/show.html.erb
<%= provide(:title, @user.name)%>


<div class="row">

  <aside class="col-md-4">
    <section class="user_info">



      <h1>
        <%= gravatar_for @user %>
       
      </h1>

    </section>


       <div style=" font-size:25px;margin-top:10px; color:black;"> Hello, <%= @user.name %></div>

  <% @user ||= current_user %>
  <a href="<%= following_user_path(@user)  %>" style= "color:black;">
 <b>   <div style = "color:black display:inline;float:left;margin-right:10px;">
      <div style = "margin-top:10px;"><%= @user.following.count %>
    following</div>
  </b></a>
</div>

 <b> <a href="<%= followers_user_path(@user) %>" style= "color:black;">
     <div style= "margin-top:10px;"> <%= @user.followers.count %>
    followers</div>
 </b> </a>

<% unless current_user?(@user) %>
  <div id="">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>


  </aside>
</div>
  

<div class = "userMenu">
	<%= link_to root_path do %>
<div class= "userBUtton">Home</div>
<% end %>


<%if current_user?(@user)%>
<%= link_to edit_user_path do%>
<div class= "userBUtton">Update</div>
<% end %>
<% end %>

<%=link_to allMeetings_path do  %>
<div class= "userBUtton">All meetings</div>
<% end %>

<%if current_user?(@user)%>
<%= link_to createMeeting_path do  %>
<div class= "userBUtton">My meetings</div>
<% end %>
<% end %>



<%= link_to users_path do  %>
<div class= "userBUtton">All users</div>
<% end %>

<%if current_user?(@user)%>
<%= link_to newmeeting_path do  %>
<div class= "userBUtton">Create meeting</div>
<% end %>
<% end %>

<%if current_user?(@user)%>

<%= button_to  @user, method: :delete, :onclick => "return confirm('Are you sure you want to delete your account?')"  do %>
<div class= "userBUtton" style="width:83px;">DELETE ACCOUNT</div>
<% end %>
<%end%>





<%if current_user?(@user)%>

<%= link_to logout_path do %>
<div class= "userBUtton">Log out</div>
<% end %>
<% end %>


</div>

   <% if @user.meetings.any? %>

<div class = "allMeetings">

      <h3 style = "color:black; margin-left:60px;">Meetings (<%= @user.meetings.count %>)</h3>
      <ol class="">
        <%= render :template => "meetings/_meetings" %>
      </ol>


    
  </div>
<% end %>

<div class = "">

  <% if @user.followed_meetings.any? %>

     <h3 style = "color:black; margin-left:90px;">Followed meeting(<%= @user.followed_meetings.count %>)</h3>

     <% @user.followed_meetings.each do |meeting| %>

  <div class = "singleMeeting"style = "margin-left:90px;">
  <div style = "float:left; position:absolute; ; z-index:-1;"> <%= image_tag meeting.picture.url, :width=>300, :height=>300  if meeting.picture? %></div>
  <div class = "meetingText" style = "z-index:-1;"><%= meeting.content.truncate(25, omission: '... (continued)') %></div>
  <div style = "color:black; display:inline; float:left; margin-top:40px; margin-left:10px;z-index:1; color: white">Posted <%= time_ago_in_words(meeting.created_at) %> ago.</div>
  </div>

</div>

<%end%>
<%end%>
</div>






  

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>



      <% if @users.any? %>
       <h3 style= "color:white"> Following users:</h3>
          <% @users.each do |user| %>

         <div class="followersGravatars">

        <div >    <%= link_to gravatar_for(user, size: 70), user %></div>
        <div >   <h3 style="color:white"> User: <%= user.name %></h3></div>
   </div>
          <%end%>
          
     
      <% end %>